#!/bin/bash

#config
servername="myserver"
serverport=4444
reportserverip=192.168.1.110
ntfytopic="komarekf-test"

#script
log=1
while :
do
    status="null"
    status=$(nc -w 1 192.168.1.110 4444)
    echo debug, status is: $status
    if (($status == 1)); then
        echo ok
        if (($log == 0)); then
            curl -d "$servername ($reportserverip) is online." ntfy.sh/$ntfytopic
            echo "$servername ($serverip) is online."
            log=1
        fi
    else
        if (($log == 1)); then
            curl -d "$servername ($reportserverip) is offline." ntfy.sh/$ntfytopic
            echo "$servername ($serverip) is offline."
            log=0
        fi
    fi
    status=null
    sleep 3
done